import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/Header";
import { PageHero } from "@/components/PageHero";
import { EditorialBlock } from "@/components/EditorialBlock";
import { ContactForm } from "@/components/ContactForm";
import { Footer } from "@/components/Footer";
import { MobileCTA } from "@/components/MobileCTA";
import { BreadcrumbSchema } from "@/components/seo/Schema";

// Veritor by the numbers — real figures pulled from production records,
// dated, and updated by hand when they change. RULE for this page: every
// number must come from the valuations database or a closing record; if a
// figure can't be regenerated by a query, it doesn't go here. Company names
// are withheld until sellers give written permission (confidentiality is
// standard on every closing) — but each closing is documented and seller
// verification is available on request during diligence.
//
// AS-OF: 2026-08-30. Update AS_OF + STATS together, from the DB.

const AS_OF = "August 30, 2026";

const STATS: Array<{ value: string; label: string; note: string }> = [
  {
    value: "260+",
    label: "Completed valuations delivered",
    note: "Sellers who ran the FMCSA-based valuation and received a written range — lifetime, since May 2026.",
  },
  {
    value: "165",
    label: "Valuations in the last 30 days",
    note: "The current monthly pace, counted from production records.",
  },
  {
    value: "41",
    label: "States sellers came from",
    note: "Distinct US states across all completed valuations.",
  },
  {
    value: "10",
    label: "Companies sold since June 2026",
    note: "Documented closings — purchase agreement, bill of sale, ownership transfer.",
  },
  {
    value: "8 of 10",
    label: "Sold companies ran Amazon Relay",
    note: "Active Relay contracts transferred with the LLC in the equity sale.",
  },
  {
    value: "9",
    label: "States closed in",
    note: "AZ, CA, DE, FL, GA, ID, IL, PA, TN — June through August 2026.",
  },
];

export const metadata: Metadata = {
  title: "Veritor by the numbers",
  description:
    "Real figures from production records, dated and updated: completed valuations, monthly pace, companies sold since June 2026, Amazon Relay share, and the states we've closed in.",
  keywords: [
    "Veritor Group track record",
    "trucking LLC sales statistics",
    "Veritor Group closed deals",
    "trucking company buyer track record",
  ],
  alternates: {
    canonical: "/transparency",
    languages: { "x-default": "/transparency" },
  },
  openGraph: {
    title: "Veritor by the numbers",
    description:
      "Completed valuations, companies sold, Relay share, states closed in — real figures, dated, from production records.",
    url: "/transparency",
    images: ["/requirements/document-table.png"],
  },
};

export default function TransparencyPage() {
  return (
    <>
      <BreadcrumbSchema
        items={[{ name: "Home", url: "/" }, { name: "By the numbers" }]}
      />
      <Header locale="en" />
      <main id="main" className="relative">
        <PageHero
          image="/requirements/document-table.png"
          alt="Ledger and documents on a desk"
          eyebrow="By the numbers"
          headlineLine1="Our track record,"
          headlineLine2="counted — not claimed."
          objectPosition="object-center"
        />

        <section className="mx-auto max-w-4xl px-5 py-10 md:px-6 md:py-14">
          <p className="mb-6 text-[12px] font-medium uppercase tracking-[0.22em] text-white/45">
            Figures as of {AS_OF} — from production records
          </p>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {STATS.map((s) => (
              <div
                key={s.label}
                className="rounded-2xl bg-white/[0.04] p-6 ring-1 ring-white/10"
              >
                <p className="text-[2rem] font-semibold leading-none text-white">
                  {s.value}
                </p>
                <p className="mt-2 text-[11px] font-semibold uppercase tracking-[0.22em] text-[#ff8a1a]">
                  {s.label}
                </p>
                <p className="mt-3 text-[13px] leading-relaxed text-white/55">{s.note}</p>
              </div>
            ))}
          </div>
        </section>

        <EditorialBlock
          eyebrow="How to read these"
          heading={
            <>
              Why the numbers are small{" "}
              <span className="italic font-light text-white/85">and why that&rsquo;s the point.</span>
            </>
          }
        >
          <p>
            Veritor Group LLC was formed in Ohio in May 2026 — the entity and its
            filings are on the <Link href="/verification">verification page</Link>.
            These figures cover the months since. We publish them dated, counted
            from the same production records that run the business, and we update
            them as they change. No round marketing numbers, nothing we
            couldn&rsquo;t defend line-by-line on a diligence call.
          </p>
          <h3>Why company names aren&rsquo;t listed — yet</h3>
          <p>
            Confidentiality is standard on every closing: most sellers don&rsquo;t
            want drivers, dispatchers, brokers, or competitors reading about their
            exit. Where sellers give written permission, we&rsquo;ll list closings
            here by company name, state, and month.{" "}
            <strong>Seller verification is available on request</strong> — a
            serious seller in diligence can ask us to connect them with a closed
            seller who has agreed to take reference calls.
          </p>
          <h3>What each closing means</h3>
          <p>
            Every &ldquo;company sold&rdquo; above is a completed corporate
            transaction: a written purchase agreement, a bill of sale for the LLC,
            funds wired at the seller&rsquo;s own bank before ownership transferred,
            and FMCSA records updated afterward — the structure described on{" "}
            <Link href="/how-it-works">how it works</Link> and committed to in the{" "}
            <Link href="/seller-protection">Seller Protection Standard</Link>.
          </p>
        </EditorialBlock>

        <ContactForm locale="en" />
      </main>
      <Footer locale="en" />
      <MobileCTA locale="en" />
    </>
  );
}
